### ISSUE TITLE
setTimeout onLineItem: TypeError: null is not an object (evaluating 'this.element.getElementsByClassName')

### ISSUE THREAD

**Issue by lightspeedbulk** [gmkarl/lightspeedbulk#22] opened 2015-10-22 15:51 UTC
Stack trace:

```
description
onLineItem

https://east15.merchantos.com/register.php?form_name=complete_all&type=special_order:34:134
nrWrapper@https://east15.merchantos.com/register.php?form_name=complete_all&type=special_order:71:12817
```

Event log:

```
onItemSearch("098652180027")
ajaxRegister_Return({"set_focus":"add_search_item_text","line_type":"register_transaction","add_line":true,"line_id":"284643","add_line_html":"\t\t\t<tr data-automation=\"saleLineItem\" class=\"popdisplay_line\" id=\"line_284643_3\">\r\n\t\t\t<td class=\"row_controls\">\r\n\t\t\t\t\t\t\t\t\t<a data-automation=\"trashBinButton\"\r\n\t\t\t\t\t   href=\"#\" class=\"control\" onclick=\"merchantos.register.removeLine(284643\r\n\t\t\t\t\t   \t); return false;\"><i class=\"icon-trash\"></i></a>\r\n\t\t\t\t\r\n\t\t\t\t\t\t\t</td>\r\n\t\t\t<td data-automation=\"saleLineItemDescription\" class=\"register-lines-control\">\r\n\t\t\t\t\t\t\t\t<a data-automation=\"saleLineItemDescriptionLink\"\r\n\t\t\t\t\thref=\"#\" onclick=\"merchantos.register.inlineEditLine('transaction_line',284643,284643); return false;\">CLINE Viognier 750ML</a>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"discountDescription\" class=\"discount\">\r\n\t\t\t\t\t\t\tDiscount:\r\n\t\t\t\t\t\t\tMember\r\n\t\t\t\t\t\t\t$-0.18\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</td>\r\n\t\t\t<td data-automation=\"saleLineItemPrice\"\r\n\t\t\t\tclass=\"popdisplay_price money\">\r\n\t\t\t\t\t\t\t\t\t$8.99\r\n\t\t\t\t\t\t\t</td>\r\n\r\n\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t<input data-automation=\"saleLineItemQuantity\"\r\n\t\t\t\t\t\t   type=\"number\" id=\"transaction_line_qout_284643\" class=\"popdisplay_quantity number xx-small\" maxlength=\"8\" tabindex=\"3000\" onchange=\"parseNumberChange(this); merchantos.register.saveDirectEdit('transaction_line','transaction_line.qout',284643,284643,getFormFieldValue(this)); return false;\" value=\"1\" onblur=\"merchantos.register.inputBlur();\"  onkeyup=\"merchantos.register.inputKeyPress(event);\" />\r\n\t\t\t\t\t\t\t</td>\r\n\t\t\t<td data-automation=\"saleLineItemTax\">\r\n\t\t\t\t\t\t\t\t\tYes\r\n\t\t\t\t\t\t\t</td>\r\n\t\t\t<td data-automation=\"saleLineItemSubtotal\"\r\n\t\t\t    class=\"popdisplay_subtotal money\">\r\n\t\t\t\t$8.81\r\n\t\t\t</td>\r\n\t\t\t\t\t</tr>\r\n\t<tr id=\"line_284643_edit\" style=\"display: none;\" class=\"edit_row\">\r\n\t<td colspan=\"6\" id=\"line_284643_edit_inner\"  class=\"line-edit\">\r\n\t</td>\r\n</tr>\r\n","totals_html":"<div class=\"register-summary\">\r\n\t<table>\r\n\t\t<tr>\r\n\t\t\t<th>Subtotal</th>\r\n\t\t\t<td id=\"popdisplay_subtotal\">$44.41</td>\r\n\t\t</tr>\r\n\t\t<tr class=\"discount\">\r\n\t\t\t<th>Discounts</th>\r\n\t\t\t<td id=\"discountValue\">\r\n\t\t\t\t\t\t\t\t\t$-0.18\r\n\t\t\t\t\t\t\t</td>\r\n\t\t</tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr data-automation=\"totalsTaxLineItem\">\r\n\t\t<th id=\"taxName_1\" data-automation=\"taxName\" >\r\n\t\t\tTax \t\t</th>\r\n\t\t<td id=\"taxValue_1\" data-automation=\"taxValue\" >\r\n\t\t\t$2.65\r\n\t\t</td>\r\n\t</tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"total\">\r\n\t\t\t\t<th id=\"totalName\">Total</th>\r\n\t\t\t\t<td id=\"sale_total\">$46.88</td>\r\n\t\t\t</tr>\r\n\t\t\t\t\t\t</table>\r\n</div>\r\n\r\n","pannel_id":0,"requests":[],"evalcode":"","success_msg":false,"failed_msg":false,"alert_msg":false,"debug":false,"add_html":null,"general_msgs":[]})
onLineItem(284643)
```

**Comment by gmkarl** [comment] 2015-10-22 17:58
This is #15 again.  The inserted html shows a valid id="line_284643_3" element.  But the error message implies that getElementById('line_284643_3') returns null.
- Add a specific check to the element getter.  If it's null, post an issue here immediately.
- Try a longer delay.  Maybe the system is waiting for something else before inserting the element.
- Maybe it's possible to add a hook on dom tree update, and respond precisely when the element is added (perhaps a better solution to a few different aspects of the script, more work)

**Comment by gmkarl** [comment] 2015-12-22 16:33
duplicate of #45

**Closed as completed by gmkarl** 2015-12-22 16:33 UTC
Labels: bug, duplicate
